### ISSUE TITLE
Enlarge the size of character

### ISSUE THREAD

**Issue by 9728627** [UCSB-CS56-Projects/cs56-games-fish-animation#101]
Right now, the size of the character(shark/whale) is fixed. The size of characters should be larger, if they eat more fishes. It is the first step to finish issue # 102. 

50XP

**Comment by xavierholt** [comment]
Closing this one in favor of https://github.com/UCSB-CS56-Projects/cs56-games-fish-animation/issues/102 - the feature described here is part of the bigger feature there.
