### ISSUE TITLE
Play again

### ISSUE THREAD

**Issue by jrcryan** [UCSB-CS56-Projects/cs56-games-fish-animation#21]
Right now the only option upon finishing the game is to exit, but the game could be improved with an option to play again

~100 points

**Comment by fstruong** [comment]
When the player wins or loses, a popup screen appears tells the player the total score and asks the player if they want to play again. If the player clicks yes, they are redirected back to main menu. If the player presses no, the window exits.

**Comment by mochele15** [comment]
Added a play again button when the user loses or wins the game. If clicked, the screen goes back to the main menu.
