### ISSUE TITLE
Menu GUI

### ISSUE THREAD

**Issue by shadeebarzin** [UCSB-CS56-Projects/cs56-games-fish-animation#24]
The current GUI for the main menu is functional, but not appealing. Improve the appearance of initial menu, maybe by adding a background image and changing button sizes so the whole menu is not 3 large buttons.

**Comment by jrcryan** [comment]
~100 points

**Comment by fstruong** [comment]
Improved the appearance of the Menu GUI with new background image and resized buttons.

**Comment by shadeebarzin** [comment]
We changed the main menu by adding a background, changing button size and locations.
We also changed the set difficulty menu by adding the background and resizing/replacing the buttons.
We also changed the instructions screen to use JTextAreas instead of a JLabel and reformatted the instructions.
