### ISSUE TITLE
Increase difficulty

### ISSUE THREAD

**Issue by shadeebarzin** [UCSB-CS56-Projects/cs56-games-fish-animation#25]
Add more enemies (ScumOfTheSea) to the more advanced levels to make them more difficult. Possible add a new level (Very Difficult) to the game with more enemies.

**Comment by jrcryan** [comment]
~150-200 points

**Comment by xavierholt** [comment]
Changing this one a bit.  Let's leave the existing levels as-is (as-are?) and add one more, harder level.  Dropping the points, 'cause this sounds very similar to what already exists.

100 XP

**Comment by xavierholt** [comment]
Having seen what it takes to do this, I'm dropping it WAY down.  And it's probably implemented in https://github.com/UCSB-CS56-Projects/cs56-games-fish-animation/pull/94.

20 XP
