### ISSUE TITLE
Update instructions for keyboard controls

### ISSUE THREAD

**Issue by fstruong** [UCSB-CS56-Projects/cs56-games-fish-animation#30]
This is dependent on issue #28. The instructions are outdated and only accounts for mouse control. More instructions should be added informing users of the different keyboard controls. Rather than simply add more text to the instructions, there should be a separate panel for the description of the game and actual key control instructions.

**Comment by jrcryan** [comment]
~50 points

**Comment by asyung** [comment]
F16 OK( 50 points)

**Comment by xavierholt** [comment]
Seems to be done as of F17.
