### ISSUE TITLE
Background Music

### ISSUE THREAD

**Issue by mochele15** [UCSB-CS56-Projects/cs56-games-fish-animation#33]
Another feature that could be added to the game could be background music. You could also have different sounds for when the shark eats the fish or hits jellyfish. It'd be nice if you could turn this on or off in the main menu.

**Comment by jrcryan** [comment]
approved
~300 points

**Comment by asyung** [comment]
F16 OK (300 pts)

**Comment by xavierholt** [comment]
Seems to be done as of F17.
