### ISSUE TITLE
Add diagonal key movement for shark

### ISSUE THREAD

**Issue by jazariethach** [UCSB-CS56-Projects/cs56-games-fish-animation#37]
Currently the shark's movement is awkward due to key listener only registering one key stroke at a time. This prevents diagonal movement since that requires two buttons to be read at once. Change this such that they key movement is smoother.

(consider using key binding or maybe logging the last pushed button if it is being held)

**Comment by jrcryan** [comment]
approved
~150 points

**Comment by sazed7** [comment]
completed and added to branch
