### ISSUE TITLE
Implement shark health

### ISSUE THREAD

**Issue by jazariethach** [UCSB-CS56-Projects/cs56-games-fish-animation#38]
Currently the shark's score is kept in the upper left corner. It dictates if the game is won or lost. Change this to represent the shark's health and consider adding a health bar instead.

**Comment by jrcryan** [comment]
approved
~100 points

**Comment by asyung** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
Probably covered by https://github.com/UCSB-CS56-Projects/cs56-games-fish-animation/issues/79, but I'll leave it here just in case.

50 XP
