### ISSUE TITLE
Glitchy Frames

### ISSUE THREAD

**Issue by jazariethach** [UCSB-CS56-Projects/cs56-games-fish-animation#39]
The game implements new frames in between screens, this causes flickering. Change this so the game is on one frame and instead use panels to change screens.

**Comment by jrcryan** [comment]
approved
~200 points

**Comment by asyung** [comment]
F16 OK (200 pts)

**Comment by xavierholt** [comment]
I haven't been able to reproduce this, so if you want points for "fixing" it you'll have to show me the flickering first!

200 XP

**Comment by xavierholt** [comment]
Fixed by https://github.com/UCSB-CS56-Projects/cs56-games-fish-animation/pull/86.
