### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by akjit** [UCSB-CS56-Projects/cs56-games-fish-animation#44]
Right now the README only says a fish animation.
We're gonna make sure everyone on github knows the amazing features of our game by displaying great screenshots and in-depth tutorials.

**Comment by mbahia** [comment]
Approved
50 pts

**Comment by asyung** [comment]
F16 OK (50 pts)

**Comment by xavierholt** [comment]
It now talks about the game, but could still use a lot more info.

50 XP
