### ISSUE TITLE
Implement Background Image changes

### ISSUE THREAD

**Issue by asyung** [UCSB-CS56-Projects/cs56-games-fish-animation#54]
Have an interactive background environment, so when the levels increase the background changes. Suggested 100 points

**Comment by mbahia** [comment]
Approved M.B.

**Comment by asyung** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
I'm interpreting this one as "each difficulty level should have a distinct background."

100 XP

**Comment by xavierholt** [comment]
Fixed by https://github.com/UCSB-CS56-Projects/cs56-games-fish-animation/pull/89.

+100 XP
