### ISSUE TITLE
Design and implement character features

### ISSUE THREAD

**Issue by keiyou** [UCSB-CS56-Projects/cs56-games-fish-animation#65]
Currently, Shark and Killer Whale are exactly the same except their appearance. Please design and implement different features for them. For example, Killer Whale would have higher initial health (thus a longer health bar), but recover less health when eating fish. On the other hand, Shark would have lower initial health but can recover health quickly by eating.

**Comment by asyung** [comment]
F16 OK (200 points)

**Comment by xavierholt** [comment]
Dropping the points on this one...

100 XP

**Comment by xavierholt** [comment]
Fixed by https://github.com/UCSB-CS56-Projects/cs56-games-fish-animation/pull/93#pullrequestreview-79675908.
