### ISSUE TITLE
Javadoc Comment Cleanup

### ISSUE THREAD

**Issue by xavierholt** [ucsb-cs56-projects/cs56-games-fish-animation#78]
My editor thinks that Javadocs with no leading asterisk should be bright pink.  My eyes hurt.  Please help.

50 XP

<img width="453" alt="screen shot 2017-10-01 at 6 42 54 pm" src="https://user-images.githubusercontent.com/1435765/31061684-a68d6be8-a6d8-11e7-8c42-4b40b49c1c36.png">

**Comment by 9728627** [comment]
I wanted to fix the bug and serached the Internet. I think you should change the color scheme. The color of the comments depends on your editor. So i do not think I fix it on my side. Is it one kind of solution to the error here?

**Comment by xavierholt** [comment]
Convention is to use the leading asterisks, and leaving them out does obviously make some editors complain.  There's also a slight difference in how code without them is interpreted.  From [the docs](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#leadingasterisks):

> When javadoc parses a doc comment, leading asterisk (`*`) characters on each line are discarded; blanks and tabs preceding the initial asterisk (`*`) characters are also discarded. Starting with 1.4, if you omit the leading asterisk on a line, the leading white space is no longer removed. This enables you to paste code examples directly into a doc comment inside a `<PRE>` tag, and its indentation will be honored. Spaces are generally interpreted by browsers more uniformly than tabs. Indentation is relative to the left margin (rather than the separator `/**` or `<PRE>` tag).

So I'd fix it.  But if you don't want the points, don't fix it.

**Comment by aryamandas** [comment]
W18 OK (50 points)

**Comment by xstephenhu98** [comment]
Fixed #78 - more leading asterisks and no more pink!
